plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/dvera/New App/.claude/worktrees/hopeful-hertz-33e4f3/furaway"
publishOrigin = "config"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]